using System.Diagnostics;
using System.Text;
using Microsoft.Win32;

namespace Lanmian;

public sealed class Cs2CfgManager
{
    private const string ManagedBlockStart = "// >>> LANMIAN MANAGED BLOCK >>>";
    private const string ManagedBlockEnd = "// <<< LANMIAN MANAGED BLOCK <<<";
    private static readonly UTF8Encoding Utf8WithoutBom = new(false);

    public string Cs2Path { get; private set; }
    public string CfgPath => string.IsNullOrWhiteSpace(Cs2Path) ? string.Empty : Path.Combine(Cs2Path, "game", "csgo", "cfg");
    public string SendCfgPath => string.IsNullOrWhiteSpace(CfgPath) ? string.Empty : Path.Combine(CfgPath, "lanmian_send.cfg");
    public string BootstrapCfgPath => string.IsNullOrWhiteSpace(CfgPath) ? string.Empty : Path.Combine(CfgPath, "lanmian_bootstrap.cfg");
    public string AutoexecPath => string.IsNullOrWhiteSpace(CfgPath) ? string.Empty : Path.Combine(CfgPath, "autoexec.cfg");

    public Cs2CfgManager(string configuredPath)
    {
        Cs2Path = ValidateCs2Path(configuredPath) ? Path.GetFullPath(configuredPath) : string.Empty;
    }

    public string DetectCs2Path()
    {
        if (ValidateCs2Path(Cs2Path)) return Cs2Path;

        var runningPath = DetectFromRunningProcess();
        if (ValidateCs2Path(runningPath)) return SetPath(runningPath);

        foreach (var library in GetSteamLibraries())
        {
            foreach (var folderName in new[] { "Counter-Strike Global Offensive", "Counter-Strike 2" })
            {
                var candidate = Path.Combine(library, "steamapps", "common", folderName);
                if (ValidateCs2Path(candidate)) return SetPath(candidate);
            }
        }

        return string.Empty;
    }

    public bool IsInstalled()
    {
        if (!File.Exists(BootstrapCfgPath) || !File.Exists(SendCfgPath) || !File.Exists(AutoexecPath)) return false;
        return File.ReadAllText(AutoexecPath).Contains(ManagedBlockStart, StringComparison.Ordinal);
    }

    public void Install(string triggerKey, bool teamChat, Meme stagedMeme)
    {
        EnsureCfgPath();
        EnsureOwnedOrAbsent(BootstrapCfgPath, "// Generated by Lanmian.");
        EnsureOwnedOrAbsent(SendCfgPath, "// Lanmian meme #");
        StageMeme(stagedMeme, teamChat);

        var bindKey = NormalizeCfgKey(triggerKey);
        var bootstrap = new[]
        {
            "// Generated by Lanmian. This file is safe to regenerate.",
            $"bind \"{bindKey}\" \"exec lanmian_send\"",
            $"echo \"Lanmian: {bindKey} is ready.\""
        };
        File.WriteAllLines(BootstrapCfgPath, bootstrap, Utf8WithoutBom);

        if (File.Exists(AutoexecPath) && !File.Exists(AutoexecPath + ".lanmian.bak"))
        {
            File.Copy(AutoexecPath, AutoexecPath + ".lanmian.bak");
        }

        var lines = File.Exists(AutoexecPath) ? File.ReadAllLines(AutoexecPath).ToList() : new List<string>();
        RemoveManagedBlock(lines);
        if (lines.Count > 0 && !string.IsNullOrWhiteSpace(lines[^1])) lines.Add(string.Empty);
        lines.Add(ManagedBlockStart);
        lines.Add("exec lanmian_bootstrap");
        lines.Add(ManagedBlockEnd);
        File.WriteAllLines(AutoexecPath, lines, Utf8WithoutBom);
    }

    public void StageMeme(Meme meme, bool teamChat)
    {
        EnsureCfgPath();
        EnsureOwnedOrAbsent(SendCfgPath, "// Lanmian meme #");
        var command = teamChat ? "say_team" : "say";
        var safeText = EscapeMessage(meme.Text);
        var content = $"// Lanmian meme #{meme.Id}{System.Environment.NewLine}{command} \"{safeText}\"{System.Environment.NewLine}";
        WriteAtomically(SendCfgPath, content);
    }

    public bool Restore()
    {
        EnsureCfgPath();
        EnsureOwnedOrAbsent(BootstrapCfgPath, "// Generated by Lanmian.");
        EnsureOwnedOrAbsent(SendCfgPath, "// Lanmian meme #");
        EnsureOwnedOrAbsent(SendCfgPath + ".tmp", "// Lanmian meme #");

        var changed = false;

        if (File.Exists(AutoexecPath))
        {
            var lines = File.ReadAllLines(AutoexecPath).ToList();
            if (RemoveManagedBlock(lines))
            {
                File.WriteAllLines(AutoexecPath, lines, Utf8WithoutBom);
                changed = true;
            }
        }

        changed |= DeleteOwnedFile(BootstrapCfgPath);
        changed |= DeleteOwnedFile(SendCfgPath);
        changed |= DeleteOwnedFile(SendCfgPath + ".tmp");
        return changed;
    }

    public static string NormalizeCfgKey(string key)
    {
        if (!KeyMap.TryNormalize(key, out var normalized)) throw new InvalidOperationException("发送键无效");
        return normalized.ToLowerInvariant();
    }

    private string SetPath(string path)
    {
        Cs2Path = Path.GetFullPath(path);
        return Cs2Path;
    }

    private void EnsureCfgPath()
    {
        if (!ValidateCs2Path(Cs2Path)) throw new InvalidOperationException("未找到有效的 CS2 安装目录");
        Directory.CreateDirectory(CfgPath);
    }

    private static bool ValidateCs2Path(string? path)
    {
        return !string.IsNullOrWhiteSpace(path) &&
               Directory.Exists(path) &&
               File.Exists(Path.Combine(path, "game", "csgo", "pak01_dir.vpk"));
    }

    private static string DetectFromRunningProcess()
    {
        try
        {
            using var process = Process.GetProcessesByName("cs2").FirstOrDefault();
            var executable = process?.MainModule?.FileName;
            if (string.IsNullOrWhiteSpace(executable)) return string.Empty;
            var executableDirectory = Path.GetDirectoryName(executable);
            return executableDirectory == null ? string.Empty : Path.GetFullPath(Path.Combine(executableDirectory, "..", "..", ".."));
        }
        catch
        {
            return string.Empty;
        }
    }

    private static IEnumerable<string> GetSteamLibraries()
    {
        var libraries = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        if (!OperatingSystem.IsWindows()) return libraries;

        try
        {
            using var steamKey = Registry.CurrentUser.OpenSubKey(@"Software\Valve\Steam");
            var steamPath = steamKey?.GetValue("SteamPath") as string;
            if (!string.IsNullOrWhiteSpace(steamPath)) libraries.Add(steamPath);

            if (!string.IsNullOrWhiteSpace(steamPath))
            {
                var libraryFile = Path.Combine(steamPath, "steamapps", "libraryfolders.vdf");
                if (File.Exists(libraryFile))
                {
                    foreach (var line in File.ReadLines(libraryFile))
                    {
                        var trimmed = line.Trim();
                        if (!trimmed.StartsWith("\"path\"", StringComparison.OrdinalIgnoreCase)) continue;
                        var parts = trimmed.Split('"', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries);
                        if (parts.Length >= 2 && Directory.Exists(parts[1])) libraries.Add(parts[1].Replace("\\\\", "\\"));
                    }
                }
            }
        }
        catch
        {
            // Registry and Steam metadata are optional detection sources.
        }

        return libraries;
    }

    private static string EscapeMessage(string message)
    {
        var builder = new StringBuilder();
        foreach (var character in message)
        {
            if (character is '\r' or '\n') builder.Append(' ');
            else if (character == ';') builder.Append('，');
            else if (character == '"') builder.Append('\'');
            else if (!char.IsControl(character)) builder.Append(character);
        }

        var result = builder.ToString().Trim();
        return result.Length <= 250 ? result : result[..250];
    }

    private static void WriteAtomically(string targetPath, string content)
    {
        var temporaryPath = targetPath + ".tmp";
        File.WriteAllText(temporaryPath, content, Utf8WithoutBom);

        for (var attempt = 0; attempt < 3; attempt++)
        {
            try
            {
                File.Move(temporaryPath, targetPath, true);
                return;
            }
            catch (IOException) when (attempt < 2)
            {
                Thread.Sleep(50);
            }
        }
    }

    private static void EnsureOwnedOrAbsent(string path, string ownershipMarker)
    {
        if (!File.Exists(path)) return;
        var content = File.ReadAllText(path);
        if (!content.StartsWith(ownershipMarker, StringComparison.Ordinal))
        {
            throw new InvalidOperationException($"检测到同名但不属于烂梗喵的 CFG，已停止操作：{Path.GetFileName(path)}");
        }
    }

    private static bool DeleteOwnedFile(string path)
    {
        if (!File.Exists(path)) return false;
        File.Delete(path);
        return true;
    }

    private static bool RemoveManagedBlock(List<string> lines)
    {
        var start = lines.FindIndex(line => line.Trim().Equals(ManagedBlockStart, StringComparison.Ordinal));
        if (start < 0) return false;

        var end = lines.FindIndex(start, line => line.Trim().Equals(ManagedBlockEnd, StringComparison.Ordinal));
        if (end < start) return false;
        lines.RemoveRange(start, end - start + 1);
        return true;
    }
}
